delivery/express/models.py
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()  # 实例化数据库对象，它提供访问Flask-SQLAlchemy的所有功能


class Delivery(db.Model):  # 所有模型的基类叫 db.Model，它存储在创建的SQLAlchemy实例上。
    # 定义表名
    __tablename__ = 'delivery'

    # 定义对象
    ID = db.Column(db.String(64), primary_key=True, unique=True, nullable=False)
    NAME = db.Column(db.Text, nullable=False)
    TEL = db.Column(db.String(64), nullable=False)
    Time = db.Column(db.DATETIME, nullable=False)
    Status = db.Column(db.Text, nullable=False)

    # __repr__()方法显示一个可读字符串，虽然不是完全必要，不过用于调试、测试是很不错的。
    def __repr__(self):
        return '<Role {}>'.format(self.name)

delivery/express/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, PasswordField
from wtforms.validators import DataRequired
import time


class boxForm(FlaskForm):
    box = StringField('快递单号', validators=[DataRequired()])
    submit = SubmitField('提交')


class deliveryForm(FlaskForm):
    id = StringField('快递单号', validators=[DataRequired()])
    name = StringField('姓名', validators=[DataRequired()])
    tel = StringField('电话号码', validators=[DataRequired()])
    time = SelectField('时间', choices=[time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))])
    status = SelectField('取件状态', choices=['未取件', '已取件'])
    submit = SubmitField('提交')


class findboxForm(FlaskForm):
    id = StringField('快递单号', validators=[DataRequired()])
    tel = StringField('电话号码', validators=[DataRequired()])
    submit = SubmitField('提交')


class loginForm(FlaskForm):
    name = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('提交')

delivery/express/__init__.py
from flask import Flask, render_template, session
from .models import *
from .forms import *
from .utils import *
from .config import Config
from .views.user import user
from .views.admin import administrator

# 初始化
app = Flask(__name__)
app.config.from_object(Config)
app.app_context().push()
db.init_app(app)
db.create_all()
app.register_blueprint(administrator)
app.register_blueprint(user)


@app.route('/')
def homepage():
    return render_template('home.html')


# @app.route("/logout")
# def logout():
#     session.pop('username', None)
#     session.pop('password', None)
#     return redirect(url_for('homepage'))

delivery/express/views/admin.py
from flask import Blueprint, flash, render_template, redirect, url_for
from express.forms import *
from express.models import *
from express.utils import redirect_back

administrator = Blueprint('admin', __name__, template_folder='templates/admin')


@administrator.route('/find', methods=['GET', 'POST'])
def find():
    box_form = boxForm()
    id = []
    if box_form.validate_on_submit():
        box_id = box_form.box.data
        state = Delivery.query.filter(Delivery.ID == box_id).first()
        if state is None:
            flash("该快递单号不存在")
        else:
            id.append(state.ID)
            row_x = [state.ID, state.NAME, state.TEL, state.Time, state.Status]
            return render_template("admin/find.html", form=box_form, row=row_x, row_id=id)
    return render_template("admin/find.html", form=box_form)


@administrator.route('/admin')
def admin():
    return render_template('admin/admin.html')


@administrator.route("/login", methods=["POST", "GET"])
def login():
    login_form = loginForm()
    if login_form.validate_on_submit():
        name = login_form.name.data
        password = login_form.password.data
        if name == 'admin' and password == 'admin':
            return redirect(url_for('admin.admin'))
        else:
            flash('用户名或密码错误!')
    return render_template('admin/login.html', form=login_form)


@administrator.route('/addbox', methods=['GET', 'POST'])
def addbox():
    delivery_form = deliveryForm()
    delivery_id = []
    if delivery_form.validate_on_submit():
        id = delivery_form.id.data
        name = delivery_form.name.data
        tel = delivery_form.tel.data
        time = delivery_form.time.data
        status = delivery_form.status.data

        flag = Delivery.query.filter_by(ID=id).first()

        if flag is not None:
            flash("输入错误，该订单号已存在，请重新输入")
        else:
            new_delivery = Delivery(ID=id, NAME=name, TEL=tel, Time=time, Status=status)
            db.session.add(new_delivery)
            db.session.commit()
            flash("提交成功")
            delivery_row = [id, name, tel, time, status]
            delivery_id.append(id)
            return render_template("admin/addbox.html", form=delivery_form, row=delivery_row, row_id=delivery_id)
    return render_template("admin/addbox.html", form=delivery_form)


@administrator.route('/list')
def list():
    rows = Delivery.query.all()
    return render_template("admin/list.html", rows=rows)


@administrator.route('/delete/<id>')
def delete(id):
    id_flag = Delivery.query.filter_by(ID=id).first()
    if id_flag is not None:
        result = Delivery.query.filter(Delivery.ID == id).first()
        db.session.delete(result)
        db.session.commit()
        flash('成功删除快递信息')
    else:
        flash("找不到该快递")
    return redirect_back('/delete/<id>')


@administrator.route('/change/<id>')
def change(id):
    state = Delivery.query.filter(Delivery.ID == id).first()
    if state.Status == '已取件':
        flash('该快递已被去除，请勿重复取件')
    else:
        state.Status = '已取件'
        db.session.commit()
        flash('成功取出该快递')
    return redirect_back('/change/<id>')

delivery/express/views/user.py
from flask import Blueprint, flash, render_template
from express.forms import *
from express.models import *
user = Blueprint('user', __name__, template_folder='templates/user')


@user.route('/user', methods=['GET', 'POST'])
def findbox():
    findbox_form = findboxForm()
    row_id = []
    if findbox_form.validate_on_submit():
        id = findbox_form.id.data
        tel = findbox_form.tel.data
        state = Delivery.query.filter(Delivery.ID == id).first()
        if state is None:
            flash("该快递单号不存在")
        else:
            id_tel = state.TEL
            if tel != id_tel:
                flash('快递单号和电话号码不匹配')
            else:
                state = Delivery.query.filter(Delivery.ID == id).first()
                row_x = [state.ID, state.NAME, state.TEL, state.Time, state.Status]
                row_id.append(id)
                return render_template("user/user.html", form=findbox_form, row=row_x, row_id=row_id)
    return render_template('user/user.html', form=findbox_form)

delivery/express/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>驿站快递管理系统</title>
</head>
<link rel="stylesheet"  type="text/css"  href="../static/style2.css" >
<h2>欢迎使用北邮驿站快递管理系统</h2>

<body class="background_">
    <fieldset>
        <legend>身份选择</legend>

    <h2><a href = "\login">管理员入口</a></h2>
    <h2><a href = "\user">我要取件</a></h2>
    </fieldset>
</body>
</html>

delivery/express/templates/user/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link rel="stylesheet" type="text/css"  href="../../static/style2.css" >

<h2>欢迎使用北邮驿站管理系统</h2>

<body class="background_">
    <fieldset>
        <legend>快递查询</legend>

<form action = "/user" method = post align="center" >
    {{ form.csrf_token()}}
    {{ form.id.label }}{{ form.id }}<br>
    {{ form.tel.label }}{{ form.tel }}<br>
    {{ form.submit }}<br>

    {% for message in get_flashed_messages()%}
        {{ message }}
    {% endfor %}
</form>
    </fieldset>

<hr>

<table border = 1 align="center">
    <thead>
        <td>快递单号</td>
        <td>姓名</td>
        <td>电话</td>
        <td>时间</td>
        <td>取件状态</td>
        <td>修改取件状态</td>
{#        <td>删除该订单</td>#}
    </thead>

<tr>
    {% for x in row %}
        <td>{{x}}</td>
    {% endfor %}
    {% for y in row_id %}
        <td><a href="{{ url_for("admin.change", id=y) }}">确认取件</a></td>
    {% endfor %}
{#    {% for y in row_id %}#}
{#        <td><a href="{{ url_for("admin.delete", id=y) }}">删除</a></td>#}
{#    {% endfor %}#}
</tr>
</table>

<h3 align="center"><a href = "/">返回主页</a></h3>
</body>
</html>